### PR TITLE
SRegionProtector support

### PR DESCRIPTION
**Pull request by SergeyDertan**
%srp_current_region% - get region by player`s pos, return region`s name or empty string
%srp_region_amount_(creator,owner,member)% - player`s regions amount
%srp_region_is_selling% - get region by player`s pos and return true if its selling
%srp_flag_state<FLAG_NAME>% - get region by player`s pos and return flag state as "allow", "deny" or empty string if region or flag not found

### CODE REVIEW

**Comment by Creeperface01** [comment]
Thank you, and don't you want to build the support for placeholders into your plugin directly it will be better, this plugin was created because authors of plugins are no longer active

**Comment by SergeyDertan** [comment]
How?

**Comment by Creeperface01** [comment]
Like you did it here

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/942fe8022abd1b57405529cf9cdd64677a1b4bb6

**Comment by Creeperface01** [comment]
Good job

**Pull request closed without merging**
